export default function personnel() {
  return [
    {
      personnelID: "35267455",
      name: "محمد",
      lastName: "حسنی احمدآبادی",
      fatherName: "علی آقا",
      birthplace: "میبد",
      nationalID: "2015234025",
      post: "سرباز معلم",
      employingUnit: "هنرستان آیت الله خاتمی",
    },
    {
      personnelID: "21524155",
      name: "رضا",
      lastName: "میر ابوالحسینی اردکانی",
      fatherName: "غلامحسین",
      birthplace: "یزد",
      nationalID: "3266554220",
      post: "مدیر",
      employingUnit: "دبیرستان سیدالشهدا (شاهد)",
    },
    {
      personnelID: "32144458",
      name: "زهرا",
      lastName: "سرافرازی",
      fatherName: "صمد",
      birthplace: "اردکان",
      nationalID: "2159556322",
      post: "معاون آموزشی",
      employingUnit: "هنرستان شاستگان",
    },
    {
      personnelID: "32875996",
      name: "سید محمد کاظم",
      lastName: "یگانه",
      fatherName: "مسعود",
      birthplace: "اردکان",
      nationalID: "214558966",
      post: "معاون پروشی",
      employingUnit: "دبیرستان شرف",
    },
    {
      personnelID: "32154785",
      name: "معصومه السادات",
      lastName: "حیدریان",
      fatherName: "محمدرضا",
      birthplace: "یزد",
      nationalID: "2158652355",
      post: "آموزگار",
      employingUnit: "دبیرستان فرزانگان شکار",
    },
    {
      personnelID: "34215586",
      name: "فرهاد",
      lastName: "کاظم پور",
      fatherName: "مصطفی",
      birthplace: "میبد",
      nationalID: "4477598423",
      post: "دبیر",
      employingUnit: "دبیرستان انصاری",
    },
    {
      personnelID: "44010320",
      name: "محسن",
      lastName: "شیدایی",
      fatherName: "مصطفی",
      birthplace: "اردکان",
      nationalID: "4440081525",
      post: "مدیر",
      employingUnit: "دبستان آسایش",
    },
    {
      personnelID: "44010321",
      name: "حمیدرضا",
      lastName: "خدائی",
      fatherName: "بمانعلی",
      birthplace: "اردکان",
      nationalID: "4440081526",
      post: "آموزگار",
      employingUnit: "دبیرستان نمونه آیت الله خامنه‌ای",
    },
    {
      personnelID: "20312000",
      name: "محمد",
      lastName: "سلیمی",
      fatherName: "جلال",
      birthplace: "یزد",
      nationalID: "6599641277",
      post: "خدمتگزار",
      employingUnit: "اداره آموزش و پرورش اردکان",
    },
    {
      personnelID: "55648256",
      name: "حسین",
      lastName: "صادقی",
      fatherName: "ابراهیم",
      birthplace: "یزد",
      nationalID: "2156975134",
      post: "راننده",
      employingUnit: "اداره آموزش و پرورش اردکان",
    },
  ];
}
